# fly.toml app configuration file generated for phonebook-backend-muddy-meadow-6648 on 2025-05-17T11:51:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-backend-muddy-meadow-6648'
primary_region = 'fra'

[build]

[env]
  PORT = "3001" # add this

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
